### ISSUE TITLE
when I call de Toggle Zoom to mouse I get this error

### ISSUE THREAD

**Issue by LeonardoSbardelotto** [BlankSourceCode/obs-zoom-to-mouse#10]
[obs-zoom-to-mouse.lua] Failed to call hotkey_pressed for hotkey_pressed: [string "C:/Program Files/obs-studio/data/obs-plugins/..."]:567: attempt to perform arithmetic on field 'x' (a nil value) 

What should I do?

**Comment by BlankSourceCode** [comment]
@LeonardoSbardelotto It sounds like the script cannot get the size/position of your display. Could you check `Enable debug logging` in the settings and tell me what the log says for `Parsing display name: xxx`. 

As a workaround, you can try enabling `Set manual source position` and enter the values for your display source (so if it's your primary monitor x=0, y=0, width=resolution of monitor width in px, height = resolution of monitor height in px, scalex = 1, scaley = 1)

**Comment by LeonardoSbardelotto** [comment]
Removed and added a new Display Capture solved the issue. Thanks
