### ISSUE TITLE
Screen blinking on DXGI Capture Method on Display Capture

### ISSUE THREAD

**Issue by dellacolletta** [BlankSourceCode/obs-zoom-to-mouse#17]
I downloaded the latest version right when I saw your update about the blinking screen. But, even with the new version, my screen still blinks when I use DXGI capture method. I would like to use this method because it removes the yellow border that Windows 10 adds to the screen that's captured. 

https://github.com/BlankSourceCode/obs-zoom-to-mouse/assets/134345624/d5dd51c2-8a0e-4c8d-ade0-f959e53ce5eb

I don't know how I can improve my feedback, so let me know if there's any other useful information that I can provide to you.

**Comment by BlankSourceCode** [comment]
Oh I see. Yeah this is a different thing to what I fixed sorry, I'm not sure about this one.

I have Windows 11, so I don't see any yellow borders when I use the `Windows 10 (1903 and up)` so I've always just used that one. When I switch it to `DXGI` instead I do see a similar flicker when changing scenes, but I seem to see it even if I remove the script(!)

Do you only see the blinking when you have the script installed? 
If you remove it (and restart OBS for good measure) does the blinking go away? If so, does it come back if you switch to `Windows 10 (1903 and up)` and then back to `DXGI` (without restarting OBS) with the script still uninstalled?

**Comment by dellacolletta** [comment]
It works!
Thank you so much for the support.

I edited the script and tested all the capture methods, Windows 10 (1903 and up) still works but now the DXGI works perfectly and flicks just right after I select the capture method. after this no more blinking annoying thing.

Again, thank you!
